#!/bin/bash
set -euo pipefail
help() { echo "run, the minimalist's task runner - https://github.com/simpzan/run"; }

build() {
  	make package FINALPACKAGE=1
	cp ./.theos/obj/xforyouautoloaddisable.dylib .
	install_name_tool -id @rpath/CydiaSubstrate.framework/CydiaSubstrate xforyouautoloaddisable.dylib
	install_name_tool -change /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate @rpath/CydiaSubstrate.framework/CydiaSubstrate xforyouautoloaddisable.dylib
	ls -alh xforyouautoloaddisable.dylib
}

install() {
  	xcrun devicectl device copy to \
		--device "AAB6300C-C853-549F-84A1-17D9DA2C20E7" \
		--domain-identifier "com.kdt.livecontainer.4NF4SBWC2N" \
		--domain-type appDataContainer \
		--destination "Documents/Tweaks/Twitter/xforyouautoloaddisable.dylib" \
		--source "xforyouautoloaddisable.dylib"
	xcrun devicectl device info files \
		--device "AAB6300C-C853-549F-84A1-17D9DA2C20E7" \
		--domain-identifier com.kdt.livecontainer.4NF4SBWC2N \
		--domain-type appDataContainer \
		--subdirectory Documents/Tweaks/

	pid=`xcrun devicectl device info processes  --device "AAB6300C-C853-549F-84A1-17D9DA2C20E7" | grep LiveContainer | awk '{print $1}' `
	echo "pid is $pid"
	xcrun devicectl device process terminate \
		--device "AAB6300C-C853-549F-84A1-17D9DA2C20E7" \
		--pid $pid
}

test() {
	set -x
	build
	install
	idevicesyslog | tee log | grep LiveContainer
}

main_() {
  if [[ -z "$@" ]]; then
    compgen -A function | grep -v "_$"
  elif declare -F "$1" >/dev/null; then
    "$@"
  else
    echo "Error: unknown function '$1'" >&2
  fi
}
main_ $@
