#!/bin/bash
set -euo pipefail
help() { echo "run, the minimalist's task runner - https://github.com/simpzan/run"; }

build() {
	export THEOS=/opt/theos
  	make package FINALPACKAGE=1
	cp ./.theos/obj/xforyouautoloaddisable.dylib .
	install_name_tool -id @rpath/CydiaSubstrate.framework/CydiaSubstrate xforyouautoloaddisable.dylib
	install_name_tool -change /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate @rpath/CydiaSubstrate.framework/CydiaSubstrate xforyouautoloaddisable.dylib
	ls -alh xforyouautoloaddisable.dylib
}

install() {
	set -x
	devctl="xcrun devicectl device"
	device="--device AAB6300C-C853-549F-84A1-17D9DA2C20E7"
	app="--domain-identifier com.kdt.livecontainer.4NF4SBWC2N --domain-type appDataContainer"

	$devctl copy to $device $app \
		--source "xforyouautoloaddisable.dylib" \
		--destination "Documents/Tweaks/Twitter/xforyouautoloaddisable.dylib"
	$devctl info files $device $app \
		--subdirectory Documents/Tweaks/

	pid=`$devctl info processes $device | grep LiveContainer | awk '{print $1}' `
	$devctl process terminate $device --pid $pid
}

test() {
	set -x
	build
	install
	idevicesyslog | tee log | grep LiveContainer
}

main_() {
  if [[ -z "$@" ]]; then
    compgen -A function | grep -v "_$"
  elif declare -F "$1" >/dev/null; then
    "$@"
  else
    echo "Error: unknown function '$1'" >&2
  fi
}
main_ $@
